### ISSUE TITLE
Tautulli card

### ISSUE THREAD

**Issue by Pliind** [sharetheloveio/sharethelove.io#11]
Cant get this to work. I've got a bland Plex-image with the text "Now Playing" as of right now, the Tautulli sensor i have today is working but this card will not display any information at all.

Can you please link any updated tautulli.py you may be using?

**Comment by swetoast** [comment]
https://github.com/custom-components/sensor.tautulli

will add it to the card

**Comment by swetoast** [comment]
it actually is in the card

**Comment by Pliind** [comment]
I had an older version of tautulli for hassio for some reason, I'm testing now with your link.

**Comment by Pliind** [comment]
Still not working, adding new .py code and replacing sensor: in config did create new sensors but doesnt show in the card.

**Comment by swetoast** [comment]
does it show under dev-info ?

**Comment by Pliind** [comment]
Not sure what to look after. Just see error logs.

**Comment by swetoast** [comment]
recommend that you open a issue on the tracker for that sensor
