### ISSUE TITLE
How do I use the attributes in the example?

### ISSUE THREAD

**Issue by 3lvl0** [sharetheloveio/sharethelove.io#12]
The tautulli sensors that work for me are all sensor.tautulli__username . The one sensor names sensor.tautulli never populates with data it's always the same and when I try to reference it in Lovelace it does not show up. Any idea how I can get the server specific sensors working for me? Like last added, bandwidth used, etc. Thank you

**Comment by ludeeus** [comment]
If you have issues with the sensor platform you should open an issue there ;)
https://github.com/custom-components/sensor.tautulli/issues
Side note, attributes like ` last added` and `bandwidth used` are not yet implemented in that sensor.
