### ISSUE TITLE
Neato Vaccum Card cleaning map image not loading

### ISSUE THREAD

**Issue by kurteknikk** [sharetheloveio/sharethelove.io#36]
I'm probably doing something wrong, because the cleaning map image in the Neato Vacuum Card is not loading.
I have a feeling that in the url where there is token=*, I should fill in my own token, but I'm not sure where to get that from, because as far as I know the Neato integration for HA is via user & pass not via token.

Any idea if that's the issue or something else ?

**Comment by swetoast** [comment]
ahh tnx for pointing out that card is outdated gonna update it today after i had my morning coffee will ping on this thread once its complete

**Comment by kurteknikk** [comment]
That's quick, awesome, thanks !

**Comment by swetoast** [comment]
updated

**Comment by kurteknikk** [comment]
Few tips/remarks about the docs for this card.

Tip for other developers:
- Resize the image.png depending on the scale of your home (in my case the image should be 1002x1278px)

Remark for you:
- You are missing the battery level sensor for the vacuum, I added mine and it works perfectly now

**Comment by swetoast** [comment]
ok will fix that in a future pr
