### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by tcastberg** [sharetheloveio/sharethelove.io#44]
Hi, love the fitbit card, but as I don't have any of the images in the card it's a bit hard to set it up. Would be nice if you could include or link to them.

**Comment by swetoast** [comment]
if its the background then we cant cause it copyrighted material the rest is available.

**Comment by timelf123** [comment]
Where is the rest available?

**Comment by ludeeus** [comment]
Google.com/images
We can't redistribute them here

**Comment by timelf123** [comment]
Ok thanks for the quick reply
