### ISSUE TITLE
tautulli-card doesn't have enough config info

### ISSUE THREAD

**Issue by fortepc** [sharetheloveio/sharethelove.io#46]
tautulli-card page needs more specific info. For example, which attributes the Tautulli component should be configured to report isn't specified, and default settings (only the `magic_title` attribute) makes the card render incorrectly. The page also needs to be a bit more specific of which sensor[s] need swapped out in the `ui-lovelace.yaml` example. 

If someone could help me understand what it should be here, I can write it up for the page and make a PR if need be.

**Comment by ludeeus** [comment]
Hi @fortepc,
What you are stating here is not true.
From the pr. user sensor that tautulli creates it is just `magic_title` that are in use.
All other values are from the main sensor.

Could the reason you have issues that you have my username in your config?
`sensor.tautulli__ludeeus`

**Comment by fortepc** [comment]
Ah! Okay. It would still probably be useful to show what the custom components configuration should be, even if it is just the default one, because I was pulling my hair out trying to figure out what I was doing wrong. Because it isn't displaying correctly for me.

**Comment by fortepc** [comment]
My issue was probably related to the other bug that I reported then.

**Comment by ludeeus** [comment]
That may be, I had to set up my tautulli server from scratch so I have to wait a bit until it has enough data for it to be useful to test that part out

**Comment by ludeeus** [comment]
@fortepc Newest version of all elements for this cards should correct this
