### ISSUE TITLE
Question: Greeter Card Setup Needs Clarification

### ISSUE THREAD

**Issue by fortepc** [sharetheloveio/sharethelove.io#48]
I'm getting hung up on "Please change the states on the following sensors" and understanding how I'm supposed to be changing the states, and what I'm  supposed to be changing the states to. The only way I know to change states is the /dev-states page in hassio, and in that context the

```
  states('yourawesome_device_tracker')
  as_timestamp(states.calendar.your_awesome_mail.attributes.start_time)
  states.calendar.your_awesome_mail.attributes.message
  change User to wanted name
```

doesn't make any sense.

**Comment by swetoast** [comment]
dunno whats so hard about it change yourawesome mail to your actual mail, the only reason i published it like that is due to i didnt want my actual email published on github.
