### ISSUE TITLE
Question: Greeter Card Setup Needs Clarification

### ISSUE THREAD

**Issue by fortepc** [sharetheloveio/sharethelove.io#49]
Okay, making a repeat issue report of #48 since it was closed and locked to prevent me from adding any more comments before I had any chance to respond to it before I was able to respond with clarification of what I'm having trouble with.

I'm getting hung up on "Please change the states on the following sensors" and understanding how I'm supposed to be changing the states, and what I'm supposed to be changing the states to. The only way I know to change states is the /dev-states page in hassio, and in that context the instructions don't make sense. 

The page says I need to change these two sensors, `greeter_card_info` and `time_of_day` and then has a code block, implying I need to change those two sensors to the code block, but that doesn't work or make any sense really, so I'm sure I'm misunderstanding it. 

I'd be happy to help contribute something to the page to make these instructions more clear for others, but I have a couple questions 

{% hint style="warning" %}
Please change the following states on the follwing sensors

* greeter\_card\_info  
* time\_of\_day  

  ```yaml
  states('yourawesome_device_tracker')
  as_timestamp(states.calendar.your_awesome_mail.attributes.start_time)
  states.calendar.your_awesome_mail.attributes.message
  change User to wanted name
  ```

{% endhint %}

This here doesn't make sense of what I'm actually supposed to do.

**Comment by swetoast** [comment]
do you have a device tracker setup ? if so change yourawesome_device_tracker to that then

same goes for mail for your calander if you got that setup again its clear as day cant really put it more bluntly

**Comment by fortepc** [comment]
But where/how, that's what I'm confused about.

The documentation seems to be implying that I need to change `sensor.greeter_card_info` and `sensor.time_of_day` state to that block of yaml, but in the context of only knowing how to change an entity's state from the /dev-info tab in home assistant, that doesn't make any sense.

I already know I need to swap out my specific entity id's for the device tracker calendar and such, but even doing that doesn't make sense

**Comment by isabellaalstrom** [comment]
You need to copy and paste the code blocks into your own configuration. Then change the name of the sensors in that copied code block to those of your sensors that you want to be displayed instead of the placeholder sensors that's put in the example.
The example obviously doesn't know the unique names of your sensors.

**Comment by fortepc** [comment]
So I'm not changing sensor states at all? Just swapping out the platform configuration with my entities, rather than the placeholders?

**Comment by fortepc** [comment]
That makes loads more sense! okay thanks!
