### ISSUE TITLE
fitbit-card: The component custom:circle-sensor-card doesn't work, can we use different card?

### ISSUE THREAD

**Issue by p1ranha** [sharetheloveio/sharethelove.io#68]
The component custom:circle-sensor-card doesn't work, can we use different card?

Also can you include graphics necessary?

**Comment by swetoast** [comment]
No its copyrighted so either google up your own image or create one :)

**Comment by ludeeus** [comment]
@p1ranha if you have issue with the circle card notify the author here <https://github.com/custom-cards/circle-sensor-card/issues> :)
