### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by mclaudiopt** [sharetheloveio/sharethelove.io#82]
hello
i have tried to use this card...i copied all exactly has in the example...but it does now switch the  lights

**Comment by ludeeus** [comment]
Which card?

**Comment by ludeeus** [comment]
This site shows a collection of community made cards/tools.

You need to go into the individual links to learn more.

General:
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins
https://www.home-assistant.io/lovelace
