### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by g0r3** [sharetheloveio/sharethelove.io#83]
Hi, I found your card templates some time ago and found them very interesting. But I am failing on a more basic level to use them. Could you please tell my, where/how I have to put the snippet? In the configuration.yaml? An other file? Which tag should I use? Thank you!

**Comment by ludeeus** [comment]
This site shows a collection of community made cards/tools.

You need to go into the individual links to learn more.

General:
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins
https://www.home-assistant.io/lovelace
