### ISSUE TITLE
Examples including groups no longer working

### ISSUE THREAD

**Issue by Tosko4** [sharetheloveio/sharethelove.io#88]
Examples using groups entities no longer work since HA 0.104
https://github.com/sharetheloveio/sharethelove.io/blob/master/monster-cards/broken-card.md

There is a way to get this groups thing back again using something like:

script:
  create_every_light_group:
    sequence:
      - service: group.set
        data_template:
          object_id: "every_light"
          entities: >
            {{ states.light |  map(attribute='entity_id') | join(',') }}

**Comment by swetoast** [comment]
mind converting this into to a pull request ?

**Comment by ludeeus** [comment]
Monster-card is deprecated, this (and all other references to it should be removed), I'll look at that later today.
